HANDLE_SUCCESS = '00000'
HANDLE_FAIL = '00001'
LOGIN_FAIL = '00002'
ERROR_MOBILE = '00003'
SOURCE_NOT_EXIST = '00004'
MONEY_NOT_ENOUGH = '00005'
ORDER_NOT_EXIST = '00006'
GET_DETAIL_SUCCESS = '00007'
METHOD_NOT_ALLOW = '00008'

FORBIDDEN_OPERATOR = '10001'
ORDER_HANDLE_SUCCESS = '10002'
NO_PERMISSION = '10003'
ERROR_STATUS = '10004'
ERROR_PARAMS = '10005'

STATUS_CODE = {
    HANDLE_SUCCESS: '请求处理成功',
    HANDLE_FAIL: '请求处理失败',
    LOGIN_FAIL: '用户名或密码错误',
    ERROR_MOBILE: '手机号格式错误',
    SOURCE_NOT_EXIST: '资源不存在',
    MONEY_NOT_ENOUGH: '余额不足',
    ORDER_NOT_EXIST: '订单不存在',
    GET_DETAIL_SUCCESS: '订单查询成功',
    METHOD_NOT_ALLOW: '该方法不存在',
    FORBIDDEN_OPERATOR: '该操作不允许',
    ORDER_HANDLE_SUCCESS: '订单处理成功',
    NO_PERMISSION: '没有权限操作',
    ERROR_STATUS: '错误的状态',
    ERROR_PARAMS: '查询参数错误'
}