# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 16:09
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='博文标题')),
                ('brief', models.CharField(default='', max_length=500, verbose_name='博文摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='博文内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('read_nums', models.IntegerField(default=0, verbose_name='阅读数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '博文详细信息',
                'verbose_name_plural': '博文详细信息',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博文分类',
                'verbose_name_plural': '博文分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
    ]
